spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:   # 该服务只作为生产者使用
      retries: 3   # 允许重传3次
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer # 默认使用json类型序列化器
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # 默认使用json类型序列化器
      acks: 1

kafka:
  topic:
    inmail-topic: inmail-topic    # 站内信topic
    event-topic: event-topic  # 待办事件topic