spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.75.100:3306/cloud-reimburse
    username: root
    password: hjh123123
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    port: 6379
    host: 192.168.75.100
    password: hjh123213
    database: 3    # 用第三个库存储，前两个个人已使用