server:
  port: 8089

api:
  url:
    api-leaf: http://localhost:8090
    api-user: http://localhost:8091
    api-roleAuth: http://localhost:8091
    api-reimburse: http://localhost:8092
    api-event: http://localhost:8093
